export const AUTH_TOKEN = "auth-token";
export const LINKS_PER_PAGE = 5;

export const MILLISECONDSPERMINUTE = 60 * 1000;
export const MILLISECONDSPERHOUR = MILLISECONDSPERMINUTE * 60;
export const MILLISECONDSPERDAY = MILLISECONDSPERHOUR * 24;
export const MILLISECONDSPERMONTH = MILLISECONDSPERDAY * 30;
export const MILLISECONDSPERYEAR = MILLISECONDSPERDAY * 365;
